# Generated by Django 5.1.6 on 2025-02-15 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0002_secretvalue_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='vault',
            name='title',
            field=models.CharField(default='Dummy', max_length=255),
            preserve_default=False,
        ),
    ]
