# Generated by Django 5.1.6 on 2025-02-15 19:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0003_vault_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='secretvalue',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='secretvalue',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
