# Generated by Django 5.1.6 on 2025-02-15 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0004_secretvalue_created_at_secretvalue_updated_at'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='secretvalue',
            table='Secrets',
        ),
        migrations.AlterModelTable(
            name='vault',
            table='Vaults',
        ),
    ]
